version: '3'

services:
  discord_bot:
    container_name: charmBot
    build: .
    volumes:
      - ./config.json:/usr/src/charmBot/config.json
      - /home/jackred/Mine_Blue/charm_reader/videos:/usr/src/charmBot/videos
    restart: always

networks:
  default:
    external:
      name: ng_network
